### ISSUE TITLE
unrecognized import path "vitessedata/dgza/dgza" (import path does not begin with hostname)

### ISSUE THREAD

**Issue by zhangguohan** [vitesse-ftian/dgtools#1]
HI, everyone.

when user go install dgtools fails .

EVN:

OS: Centos 7.2 

[root@mdw ~]# cat .bash_profile 

export GOROOT=/usr/local/go
export GOPATH=/tmp/go
export PATH=$PATH:$HOME/bin:$GOROOT/bin

#PATH=$PATH:$HOME/bin:/usr/local/go/bin

export PATH
[root@mdw ~]# echo $GOROOT
/usr/local/go
[root@mdw ~]# echo $GOPATH
/tmp/go
[root@mdw ~]# go version
go version go1.9 linux/amd64
[root@mdw ~]# cd /usr/local/src/dgtools/zabbix/
[root@mdw zabbix]# make
cd src/vitessedata/dgza && go get . && go install
package vitessedata/dgza/dgza: unrecognized import path "vitessedata/dgza/dgza" (import path does not begin with hostname)
make: *** [build] 错误 1
[root@mdw zabbix]#

**Comment by vitesse-ftian** [comment]
Please add zabbix to GOPATH, in zabbix dir, do the following in bash, 

export GOPATH=$GOPATH:$PWD

Then make.

**Comment by vitesse-ftian** [comment]
Updated README.

**Comment by zhangguohan** [comment]
@vitesse-ftian  This is OK,  Thank you!
add zabbix to GOPATH,
export GOPATH=$GOPATH:/usr/local/src/dgtools/zabbix
